name: Pull Request CI

on:
  - pull_request

jobs:
  formatting-check:
    name: Formatting Check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@f62da5e3d3a2d88ff364771d9d938773a618ab5e
        with:
          check-path: 'src/nginx_module'
          clang-format-version: '16'
